window:
  decorations: buttonless
  option_as_alt: "OnlyLeft"
font:
  normal:
    family: "JetBrainsMono Nerd Font"
    style: Regular
  size: 17
cursor:
  style:
    shape: Block
    blinking: Never
key_bindings:
  - {key: Space, mods: Control, chars: "\0"}
  - {key: PageUp, action: ScrollPageUp}
  - {key: PageDown, action: ScrollPageDown}
  - {key: Home, action: ScrollToTop}
  - {key: End, action: ScrollToBottom}
  - {key: N, mods: Command, action: SpawnNewInstance}
selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'

# TokyoNight Alacritty Colors
colors:
  primary:
    background: '0x24283b'
    foreground: '0xc0caf5'
  normal:
    black: '0x1d202f'
    red: '0xf7768e'
    green: '0x9ece6a'
    yellow: '0xe0af68'
    blue: '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan: '0x7dcfff'
    white: '0xa9b1d6'
  bright:
    black: '0x414868'
    red: '0xf7768e'
    green: '0x9ece6a'
    yellow: '0xe0af68'
    blue: '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan: '0x7dcfff'
    white: '0xc0caf5'
  indexed_colors:
    - {index: 16, color: '0xff9e64'}
    - {index: 17, color: '0xdb4b4b'}
